local scriptSettings = ac.INIConfig.scriptSettings()

local cfg = scriptSettings:mapConfig({
  SETTINGS = {
    VIEW_LOCK = 0,                 -- 0 = Car, 1 = Filter, 2 = Horizon
    HORIZON_LOCK_STRENGTH = 0.5,
    --VIEW_FILTER_TIME = 0.20,

    -- Master output multipliers
    POSITION_MULT = 1.0,
    ROTATION_MULT = 1.0,
  },

  PROFILE = {
    PRF_POSITION = 0,       -- 0 Basic  /  1 Alternatively (PROFILE2)  
  },

  POSITION = {
    PITCH_VIEW = 0.00,
    ROLL_VIEW  = 0.00,
    YAW_VIEW   = 0.00,

    X_OFFSET = 0.000,
    Y_OFFSET = 0.000,
    Z_OFFSET = 0.000,
  },

  POSITION_PROFILE2 = {
    PITCH_VIEW = -4.00,
    ROLL_VIEW  = 10.00,
    YAW_VIEW   = 6.00,

    X_OFFSET = 0.090,
    Y_OFFSET = -0.120,
    Z_OFFSET = 0.040,
  },

  HIDE = {
    HIDDEN = 0,
  },

  LOCK = {
    LOCK_FUNCTION = 2,             -- 0 Joystick / 1 Axis / 2 Steer / 3 Mouse X / 4 Mouse XY
    LOOK_SENSITIVITY = 1.0,
    LOOK_CENTRE_REDUCTION = 0.0,
    BUTTON_LOOK = 0,
  },

  SHIFT = {

    -- ============================================================
    -- HEAD ROTATION
    -- ============================================================

    -- Steering → head yaw
    STEER_YAW = 0.50,

    -- Steering-rate compensation
    -- Unit: normalized steer / second
    STEER_RATE_START = 1.5,
    STEER_RATE_FULL  = 5.0,

    -- Equal or above this rate:
    -- treat steering change as a transient spike
    STEER_SPIKE_RATE = 6.0,

    -- Final steering head-yaw response
    STEER_YAW_HALFLIFE = 0.10,

    MAX_STEER_YAW = 12.0,          -- degrees

    -- Lateral G → head roll
    LATERAL_ROLL = 1.00,
    MAX_HEAD_ROLL = 3.0,            -- degrees
    HEAD_ROLL_HALFLIFE = 0.080,

    -- Longitudinal G → head pitch
    LONGITUDINAL_PITCH = 0.50,
    MAX_HEAD_PITCH = 2.0,           -- degrees
    HEAD_PITCH_HALFLIFE = 0.080,


    -- ============================================================
    -- HEAD POSITION
    -- ============================================================

    -- Suspension movement → vertical head bob
    SUSPENSION_BOB = 1.00,
    SUSPENSION_BOB_SCALE = 0.05,
    MAX_SUSPENSION_BOB = 0.015,     -- meters
    SUSPENSION_BOB_HALFLIFE = 0.020,

    -- Lateral G → side displacement
    LATERAL_SHIFT = 0.010,          -- meters / G
    MAX_LATERAL_SHIFT = 0.035,      -- meters
    LATERAL_SHIFT_BLEND = 0.120,

    -- Longitudinal G → forward/back displacement
    FORWARD_SHIFT = 0.015,          -- meters / G
    MAX_FORWARD_SHIFT = 0.040,      -- meters
    FORWARD_SHIFT_BLEND = 0.120,
    
    BRAKE_FORWARD_MULT = 0.35,
    BRAKE_FORWARD_MAX = 0.015,

    ACCEL_FORWARD_MULT = 1.00,
    ACCEL_FORWARD_MAX = 0.005,


    -- Vertical G → vertical displacement
    VERTICAL_SHIFT = 0.008,         -- meters / G
    MAX_VERTICAL_SHIFT = 0.025,     -- meters
    VERTICAL_SHIFT_BLEND = 0.120,




    -- ============================================================
    -- OPTIONAL PHYSICS RESPONSE
    -- ============================================================

    -- Small amount of lateral head movement caused by steering.
    -- This is separate from lateral G.
    STEER_SHIFT = 0.002,

    -- Additional head pitch generated by braking/acceleration.
    LONGITUDINAL_PITCH_MULT = 1.0,
  }
})


-- ========================================================================
-- Steer-Look adjustments
-- ========================================================================

local prevSteerNorm = 0.0


-- ========================================================================
-- Exact exponential damper
-- ========================================================================

local LN2 = 0.69314718056

local function damper_exact(x, goal, halflife, dt)
  halflife = math.max(halflife, 0.0001)

  return goal
    + (x - goal)
    * math.exp(-(LN2 * dt) / halflife)
end


-- ========================================================================
-- Inertial easing
-- ========================================================================

local function ie_new()
  return {
    et = 1.0,
    es = 0.0,
    eo = 0.0,
    prev = nil,
    vel = 0.0
  }
end


local function ie_eval(et, es)

  if et >= 1.0 then
    return es
  end

  return es * (3 * et * et - 2 * et * et * et)
end


local function ie_eval_vel(et, es, blendtime)

  if et >= 1.0 then
    return 0.0
  end

  return es * (6 * et - 6 * et * et) / blendtime
end


local function ie_solve(x, v, overshoot, eps)

  overshoot = overshoot or 0.05
  eps = eps or 1e-8

  if math.abs(v) < eps then
    return 0.0, x
  end

  if x < 0.0 then

    local t, s = ie_solve(
      -x,
      -v,
      overshoot,
      eps
    )

    return t, -s
  end

  local disc =
    math.max(
      (6 * x - v) * (6 * x - v)
      + 8 * v * v,
      eps
    )

  local sq = math.sqrt(disc)

  local t0 =
    (v - 6 * x + sq)
    / (4 * v)

  local t1 =
    (v - 6 * x - sq)
    / (4 * v)

  local t =
    (-0.5 > t1 and t1 > -(0.5 + overshoot))
    and t1
    or t0

  local vt =
    (t < 1.0)
    and (6 * t - 6 * t * t)
    or 0.0

  local s =
    math.abs(vt) < eps
    and 0.0
    or v / vt

  return t, s
end


local function ie_update(
  state,
  current,
  target,
  blendtime,
  dt
)

  blendtime = math.max(blendtime, 1e-4)

  if state.prev ~= target then

    local dist = target - current

    state.et, state.es =
      ie_solve(
        dist,
        state.vel * blendtime
      )

    state.eo =
      current - ie_eval(
        state.et,
        state.es
      )

    state.prev = target
  end

  state.et =
    state.et + dt / blendtime

  local value =
    state.eo
    + ie_eval(
      state.et,
      state.es
    )

  state.vel =
    ie_eval_vel(
      state.et,
      state.es,
      blendtime
    )

  return value
end


-- ========================================================================
-- Persistent state
-- ========================================================================

local dtAvg = 1 / 60

local filteredPitch = 0.0
local filteredRoll  = 0.0

local prevSusp = nil

-- Suspension bob
local suspensionBob = 0.0

-- Head rotation
local headYaw   = 0.0
local headRoll  = 0.0
local headPitch = 0.0

-- Position inertia
local ieLateral  = ie_new()
local ieForward  = ie_new()
local ieVertical = ie_new()

local curLateral  = 0.0
local curForward  = 0.0
local curVertical = 0.0


-- ========================================================================
-- Video configuration
-- ========================================================================

local vidCfg =
  ac.INIConfig.load(
    ac.getFolder(ac.FolderID.Cfg)
    .. "/video.ini"
  )

local lastHidden = -1


-- ========================================================================
-- Main update
-- ========================================================================

function script.update(dt, mode, turnMix)

  -- ------------------------------------------------------------
  -- Delta time stabilization
  -- ------------------------------------------------------------

  if dt > 0.25 then
    dt = 0.25
  end

  dtAvg =
    dtAvg
    + (dt - dtAvg) * 0.1

  local rdt = dtAvg


  -- ============================================================
  -- BASIC CAR BASIS
  -- ============================================================

  local flatForward =
    vec3(
      car.look.x,
      0,
      car.look.z
    ):normalize()


  local carPitch =
    math.asin(
      math.clamp(
        car.look.y,
        -1.0,
        1.0
      )
    )

  local carRoll =
    math.atan2(
      car.side.y,
      car.up.y
    )


  -- ============================================================
  -- SUSPENSION → HEAD BOB
  -- ============================================================

  local suspNow =
    (
      car.wheels[0].suspensionTravel
      + car.wheels[1].suspensionTravel
      + car.wheels[2].suspensionTravel
      + car.wheels[3].suspensionTravel
    ) * 0.25


  local heaveVel = 0.0

  if prevSusp ~= nil then

    heaveVel =
      (suspNow - prevSusp)
      / (rdt + 1e-8)

  end

  prevSusp = suspNow


  local rawBob =
    heaveVel
    * cfg.SHIFT.SUSPENSION_BOB
    * cfg.SHIFT.SUSPENSION_BOB_SCALE


  rawBob =
    math.clamp(
      rawBob,
      -cfg.SHIFT.MAX_SUSPENSION_BOB,
       cfg.SHIFT.MAX_SUSPENSION_BOB
    )


  suspensionBob =
    damper_exact(
      suspensionBob,
      rawBob,
      cfg.SHIFT.SUSPENSION_BOB_HALFLIFE,
      rdt
    )


    -- ============================================================
  -- STEERING → HEAD YAW
  -- ============================================================

  local steerNorm =
    math.clamp(
      -car.steer
      / math.max(car.steerLock, 1.0),
      -1.0,
      1.0
    )


  local dz =
    math.clamp(
      cfg.LOCK.LOOK_CENTRE_REDUCTION,
      0.0,
      0.99
    )


  local absSteer =
    math.abs(steerNorm)


  local finalSteer = 0.0

  if absSteer >= dz then

    finalSteer =
      (
        (absSteer - dz)
        / (1.0 - dz)
      )
      * math.sign(steerNorm)

  end


  -- ------------------------------------------------------------
  -- Steering-rate detection
  -- ------------------------------------------------------------

  local steerRate = 0.0

  if rdt > 0.0001 then
    steerRate =
      (steerNorm - prevSteerNorm)
      / rdt
  end

  local steerRateAbs =
    math.abs(steerRate)


  -- ------------------------------------------------------------
  -- Steering response compensation
  --
  -- Slow steering:
  --     full head-follow response
  --
  -- Fast steering:
  --     progressively reduce head-follow response
  --
  -- Very fast steering:
  --     keep previous target and ignore the spike
  -- ------------------------------------------------------------

  local steerResponse =
    1.0 - math.saturate(
      (
        steerRateAbs
        - cfg.SHIFT.STEER_RATE_START
      )
      / math.max(
        cfg.SHIFT.STEER_RATE_FULL
        - cfg.SHIFT.STEER_RATE_START,
        0.001
      )
    )


  local filteredSteer =
    steerNorm * steerResponse
    + prevSteerNorm * (1.0 - steerResponse)


  local targetYaw =
    filteredSteer
    * cfg.SHIFT.STEER_YAW
    * math.rad(
      cfg.SHIFT.MAX_STEER_YAW
    )


  -- ------------------------------------------------------------
  -- Spike rejection
  --
  -- Do not create a new yaw target from an abrupt steering event.
  -- The existing headYaw continues naturally toward its previous
  -- target instead.
  -- ------------------------------------------------------------

  if steerRateAbs >= cfg.SHIFT.STEER_SPIKE_RATE then

    targetYaw =
      headYaw

  end


  prevSteerNorm =
    steerNorm


  -- ------------------------------------------------------------
  -- Smooth final head yaw
  -- ------------------------------------------------------------

  headYaw =
    damper_exact(
      headYaw,
      targetYaw,
      cfg.SHIFT.STEER_YAW_HALFLIFE,
      rdt
    )



  -- ============================================================
  -- LATERAL G → HEAD ROLL
  -- ============================================================

  local targetRoll =
    car.acceleration.y
    * cfg.SHIFT.LATERAL_ROLL
    * math.rad(
      cfg.SHIFT.MAX_HEAD_ROLL
    )


  targetRoll =
    math.clamp(
      targetRoll,
      -math.rad(cfg.SHIFT.MAX_HEAD_ROLL),
       math.rad(cfg.SHIFT.MAX_HEAD_ROLL)
    )


  headRoll =
    damper_exact(
      headRoll,
      targetRoll,
      cfg.SHIFT.HEAD_ROLL_HALFLIFE,
      rdt
    )


  -- ============================================================
  -- LONGITUDINAL G → HEAD PITCH
  -- ============================================================

  local targetPitch =
    -car.acceleration.x
    * cfg.SHIFT.LONGITUDINAL_PITCH
    * math.rad(
      cfg.SHIFT.MAX_HEAD_PITCH
    )
    * cfg.SHIFT.LONGITUDINAL_PITCH_MULT


  targetPitch =
    math.clamp(
      targetPitch,
      -math.rad(cfg.SHIFT.MAX_HEAD_PITCH),
       math.rad(cfg.SHIFT.MAX_HEAD_PITCH)
    )


  headPitch =
    damper_exact(
      headPitch,
      targetPitch,
      cfg.SHIFT.HEAD_PITCH_HALFLIFE,
      rdt
    )


  -- ============================================================
  -- G-FORCE → POSITION
  -- ============================================================

  local targetLateral =
    -car.acceleration.y
    * cfg.SHIFT.LATERAL_SHIFT


  local targetForward = 0.0
    -- -car.acceleration.x
    -- * cfg.SHIFT.FORWARD_SHIFT


  local targetVertical = 0.0
    -- car.acceleration.z
    -- * cfg.SHIFT.VERTICAL_SHIFT

  
  targetLateral =
  math.clamp(
    targetLateral,
    -cfg.SHIFT.MAX_LATERAL_SHIFT,
    cfg.SHIFT.MAX_LATERAL_SHIFT
  )
  
  
  -- targetForward =
  -- math.clamp(
  --   targetForward,
  --   -cfg.SHIFT.MAX_FORWARD_SHIFT,
  --   cfg.SHIFT.MAX_FORWARD_SHIFT
  -- )
  
  
  if car.acceleration.z > 0 then
    
    local accelG = math.max(car.acceleration.z, 0)

    targetForward =
    math.min(
      accelG
        * cfg.SHIFT.VERTICAL_SHIFT 
        * cfg.SHIFT.ACCEL_FORWARD_MULT,
        cfg.SHIFT.ACCEL_FORWARD_MAX
    )
    
  elseif car.acceleration.z < 0 then
    
    local brakeG = math.max(-car.acceleration.z, 0)

    targetForward =
      math.min(
        brakeG
        * cfg.SHIFT.VERTICAL_SHIFT 
        * cfg.SHIFT.BRAKE_FORWARD_MULT,
        cfg.SHIFT.BRAKE_FORWARD_MAX
    )
  end


  targetVertical =
    math.clamp(
      targetVertical,
      -cfg.SHIFT.MAX_VERTICAL_SHIFT,
       cfg.SHIFT.MAX_VERTICAL_SHIFT
    )


  curLateral =
    ie_update(
      ieLateral,
      curLateral,
      targetLateral,
      cfg.SHIFT.LATERAL_SHIFT_BLEND,
      rdt
    )


  curForward =
    ie_update(
      ieForward,
      curForward,
      targetForward,
      cfg.SHIFT.FORWARD_SHIFT_BLEND,
      rdt
    )


  curVertical =
    ie_update(
      ieVertical,
      curVertical,
      targetVertical,
      cfg.SHIFT.VERTICAL_SHIFT_BLEND,
      rdt
    )


  -- ============================================================
  -- RESET WHEN SLOW / AIRBORNE
  -- ============================================================

  if car.justJumped or car.speedMs < 1.0 then

    suspensionBob = 0.0

    curLateral  = 0.0
    curForward  = 0.0
    curVertical = 0.0

    headRoll  = 0.0
    headPitch = 0.0
    headYaw   = 0.0

  end


  -- ============================================================
  -- VIEW LOCK
  -- ============================================================

  if cfg.SETTINGS.VIEW_LOCK == 0 then

    -- Car locked.
    -- Do not interfere with NeckFX base orientation.

  elseif cfg.SETTINGS.VIEW_LOCK == 1 then

    neck.look:setLerp(
      neck.look,
      flatForward,
      turnMix
    )

    local pitchAxis =
      vec3Normalize(
        vec3Cross(
          flatForward,
          vec3(0, 1, 0)
        )
      )

    neck.look =
      vec3Rotate(
        neck.look,
        pitchAxis,
        filteredPitch
      )

    neck.up =
      vec3Rotate(
        vec3(0, 1, 0),
        flatForward,
        filteredRoll
      )

  elseif cfg.SETTINGS.VIEW_LOCK == 2 then

    local horizonPitch =
      carPitch
      * (
        1.0
        - cfg.SETTINGS.HORIZON_LOCK_STRENGTH
      )

    local horizonRoll =
      carRoll
      * (
        1.0
        - cfg.SETTINGS.HORIZON_LOCK_STRENGTH
      )

    neck.look:setLerp(
      neck.look,
      flatForward,
      turnMix
    )

    local pitchAxis =
      vec3Normalize(
        vec3Cross(
          flatForward,
          vec3(0, 1, 0)
        )
      )

    neck.look =
      vec3Rotate(
        neck.look,
        pitchAxis,
        horizonPitch
      )

    neck.up =
      vec3Rotate(
        vec3(0, 1, 0),
        flatForward,
        horizonRoll
      )

  end


  -- ============================================================
  -- DRIVER / WHEEL VISIBILITY
  -- ============================================================

  if vidCfg.sections.ASSETTOCORSA
      and cfg.HIDE.HIDDEN ~= lastHidden then

    lastHidden =
      cfg.HIDE.HIDDEN

    if cfg.HIDE.HIDDEN == 0 then

      vidCfg:setAndSave(
        "ASSETTOCORSA",
        "HIDE_STEER",
        "0"
      )

      vidCfg:setAndSave(
        "ASSETTOCORSA",
        "HIDE_ARMS",
        "0"
      )

    elseif cfg.HIDE.HIDDEN == 1 then

      vidCfg:setAndSave(
        "ASSETTOCORSA",
        "HIDE_STEER",
        "0"
      )

      vidCfg:setAndSave(
        "ASSETTOCORSA",
        "HIDE_ARMS",
        "1"
      )

    elseif cfg.HIDE.HIDDEN == 2 then

      vidCfg:setAndSave(
        "ASSETTOCORSA",
        "HIDE_STEER",
        "1"
      )

      vidCfg:setAndSave(
        "ASSETTOCORSA",
        "HIDE_ARMS",
        "0"
      )

    end
  end


  -- ============================================================
  -- MANUAL LOOK / STEERING
  -- ============================================================

  if cfg.LOCK.LOCK_FUNCTION == 2 then

    -- neck.look:addScaled(
    --   car.side,
    --   finalSteer
    --   * cfg.LOCK.LOOK_SENSITIVITY
    --   * 0.5
    -- )

  end


  -- ============================================================
  -- POSITION OFFSETS
  -- ============================================================

  if cfg.PROFILE.PRF_POSITION == 0 then

    neck.position:addScaled(
      neck.side,
      cfg.POSITION.X_OFFSET
      * cfg.SETTINGS.POSITION_MULT
    )

    neck.position:addScaled(
      neck.look,
      cfg.POSITION.Y_OFFSET
      * cfg.SETTINGS.POSITION_MULT
    )

    neck.position:addScaled(
      neck.up,
      cfg.POSITION.Z_OFFSET
      * cfg.SETTINGS.POSITION_MULT
    )
    
  elseif cfg.PROFILE.PRF_POSITION == 1 then

    neck.position:addScaled(
      neck.side,
      cfg.POSITION_PROFILE2.X_OFFSET
      * cfg.SETTINGS.POSITION_MULT
    )

    neck.position:addScaled(
      neck.look,
      cfg.POSITION_PROFILE2.Y_OFFSET
      * cfg.SETTINGS.POSITION_MULT
    )

    neck.position:addScaled(
      neck.up,
      cfg.POSITION_PROFILE2.Z_OFFSET
      * cfg.SETTINGS.POSITION_MULT
    )
  end


  -- ============================================================
  -- PHYSICAL HEAD POSITION
  -- ============================================================

  local posMult =
    cfg.SETTINGS.POSITION_MULT


  -- Suspension bob
  neck.position:addScaled(
    neck.up,
    suspensionBob * posMult
  )


  -- Lateral inertia
  neck.position:addScaled(
    neck.side,
    curLateral * posMult
  )


  -- Longitudinal inertia
  neck.position:addScaled(
    neck.look,
    curForward * posMult
  )


  -- Vertical inertia
  neck.position:addScaled(
    neck.up,
    curVertical * posMult
  )


  -- Small steering-related body shift
  neck.position:addScaled(
    neck.side,
    finalSteer
    * cfg.SHIFT.STEER_SHIFT
    * posMult
  )

if ac.getSim().frame % 30 == 0 then
  ac.debug(
    'HEAD POS',
    string.format(
      'lat %.4f  fwd %.4f  vert %.4f  bob %.4f',
      curLateral * posMult,
      curForward * posMult,
      curVertical * posMult,
      suspensionBob * posMult
    )
  )
end
  -- ============================================================
  -- PHYSICAL HEAD ROTATION
  -- ============================================================

  local rotMult =
    cfg.SETTINGS.ROTATION_MULT


  -- ------------------------------------------------------------
  -- Head yaw
  -- ------------------------------------------------------------

  neck.look =
    vec3Rotate(
      neck.look,
      neck.up,
      headYaw * rotMult
    )


  -- ------------------------------------------------------------
  -- Head pitch
  -- ------------------------------------------------------------

  neck.look =
    vec3Rotate(
      neck.look,
      neck.side,
      headPitch * rotMult
    )


  -- ------------------------------------------------------------
  -- Head roll
  -- ------------------------------------------------------------

  neck.up =
    vec3Rotate(
      neck.up,
      neck.look,
      headRoll * rotMult
    )


  -- ============================================================
  -- USER CAMERA OFFSETS
  -- ============================================================

  local pitch = 0.0
  
  local roll = 0.0
  
  local yaw = 0.0
  
  
  if cfg.PROFILE.PRF_POSITION == 0 then

    pitch = 
      math.rad(
      cfg.POSITION.PITCH_VIEW
      )

    roll = 
      math.rad(
        cfg.POSITION.ROLL_VIEW
      )

    yaw = 
      math.rad(
        cfg.POSITION.YAW_VIEW
      )


  elseif cfg.PROFILE.PRF_POSITION == 1 then

    pitch = 
      math.rad(
      cfg.POSITION_PROFILE2.PITCH_VIEW
      )

    roll = 
      math.rad(
        cfg.POSITION_PROFILE2.ROLL_VIEW
      )

    yaw = 
      math.rad(
        cfg.POSITION_PROFILE2.YAW_VIEW
      )      

  end


  neck.look =
    vec3Rotate(
      neck.look,
      neck.side,
      pitch
    )

  neck.up:addScaled(
    neck.side,
    roll
  )

  neck.look:addScaled(
    neck.side,
    yaw
  )

end


-- ========================================================================
-- Vector helpers
-- ========================================================================

function vec3Rotate(
  vector,
  axis,
  angle
)

  local c = math.cos(angle)
  local s = math.sin(angle)

  local d =
    vec3Dot(
      axis,
      vector
    )

  return
    vector * c
    + vec3Cross(axis, vector) * s
    + axis * (
      d * (1 - c)
    )
end


function vec3Normalize(v)

  local len =
    math.sqrt(
      v.x * v.x
      + v.y * v.y
      + v.z * v.z
    )

  if len < 1e-8 then
    return vec3(0, 1, 0)
  end

  return vec3(
    v.x / len,
    v.y / len,
    v.z / len
  )
end


function vec3Cross(v1, v2)

  return vec3(
    v1.y * v2.z
      - v1.z * v2.y,

    v1.z * v2.x
      - v1.x * v2.z,

    v1.x * v2.y
      - v1.y * v2.x
  )
end


function vec3Dot(v1, v2)

  return
    v1.x * v2.x
    + v1.y * v2.y
    + v1.z * v2.z
end


function math.lerp(a, b, t)
  return a + (b - a) * t
end